output "service_endpoints" {
  value = <<-EOT
    HAOS UI:        http://homeassistant.local:8123  (DHCP on ${var.bridge_name}, check router leases)
    Frigate UI:     http://<host-ip>:5000
    Ollama API:     http://<host-ip>:11434
    Whisper (Wyoming): <host-ip>:10300
    Piper   (Wyoming): <host-ip>:10200
    Mosquitto MQTT: <host-ip>:1883
    Matter server: <host-ip>:5580 (WebSocket - add via HA's Matter integration)
    UniFi OS Server: https://<unifi-vm-ip>:11443 (bridged VM, own DHCP address - check `incus list unifi` or router leases; initial setup wizard on first load - can take a few minutes on first boot)
    ESPHome dashboard: http://<host-ip>:6052

    Thread/Zigbee radio is passed through to the HAOS VM itself (not a
    container) - configure OTBR/Zigbee via HAOS's own add-ons store.

    Wire these into HA:
      - Settings > Devices & Services > MQTT           -> host-ip:1883
      - Settings > Devices & Services > Wyoming Protocol -> add whisper and piper each as their own entry (host-ip:port)
      - Settings > Voice Assistants > Assist -> pick the whisper/piper entries, then add Ollama as the conversation agent
      - Frigate: install the Frigate HA integration, point at http://<host-ip>:5000, camera RTSP streams configured in /var/incus-volumes/frigate/config/config.yml (not generated by this repo - Frigate config is camera-specific, tell me your camera RTSP URLs and I'll template it)
      - m5stack Atom Echo S3R voice satellites: these are standalone ESP32-S3
        devices, not containers - flash each one from the ESPHome dashboard
        above using the "Voice Assistant" / media_player+microphone example
        config (ESPHome ships a template for this exact board), give it your
        WiFi creds, then in HA add it via Settings > Devices & Services ->
        it should auto-discover as an ESPHome device once flashed and on the
        LAN. Assign it to your Assist pipeline as a voice satellite - it
        streams audio straight to HA over the native API, it does not talk
        to whisper/piper directly.
  EOT
}
